package io.smallrye.ffm.test;

import static org.junit.jupiter.api.Assertions.*;
import static org.junit.jupiter.api.Assumptions.*;

import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;

import org.junit.jupiter.api.Test;

import io.smallrye.ffm.In;
import io.smallrye.ffm.Link;
import io.smallrye.ffm.Out;

/**
 * Tests for {@code MemorySegment[]} parameter marshalling with {@link In @In}/{@link Out @Out} semantics.
 * Verifies that the generated bytecode correctly copies pointer addresses to and from native memory.
 */
public final class SegmentArrayTest {

    /**
     * Construct a new instance.
     */
    public SegmentArrayTest() {
    }

    /**
     * Verify that {@code @In MemorySegment[]} correctly copies segment addresses into native memory.
     * Uses {@code memcpy} to copy the marshalled pointer array into a destination buffer,
     * then reads the addresses back to confirm they match.
     */
    @Test
    public void testSegmentArrayIn() {
        assumeTrue(SegmentArrayTest.class.getModule().isNativeAccessEnabled());
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment seg1 = arena.allocate(8);
            MemorySegment seg2 = arena.allocate(8);
            MemorySegment seg3 = arena.allocate(8);
            MemorySegment[] ptrs = { seg1, seg2, seg3 };
            long size = 3 * ValueLayout.ADDRESS.byteSize();
            MemorySegment dest = arena.allocate(ValueLayout.ADDRESS, 3);
            copyIn(dest, ptrs, size);
            assertEquals(seg1.address(), dest.getAtIndex(ValueLayout.ADDRESS, 0).address());
            assertEquals(seg2.address(), dest.getAtIndex(ValueLayout.ADDRESS, 1).address());
            assertEquals(seg3.address(), dest.getAtIndex(ValueLayout.ADDRESS, 2).address());
        }
    }

    /**
     * Verify that {@code @Out MemorySegment[]} correctly copies addresses from native memory
     * back into the Java array after the call.
     * Sets up a source buffer with known addresses, uses {@code memcpy} to copy them
     * into the (out-only allocated) backing segment, and verifies the array is populated.
     */
    @Test
    public void testSegmentArrayOut() {
        assumeTrue(SegmentArrayTest.class.getModule().isNativeAccessEnabled());
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment seg1 = arena.allocate(8);
            MemorySegment seg2 = arena.allocate(8);
            MemorySegment src = arena.allocate(ValueLayout.ADDRESS, 2);
            src.setAtIndex(ValueLayout.ADDRESS, 0, seg1);
            src.setAtIndex(ValueLayout.ADDRESS, 1, seg2);
            MemorySegment[] ptrs = new MemorySegment[2];
            long size = 2 * ValueLayout.ADDRESS.byteSize();
            copyOut(ptrs, src, size);
            assertEquals(seg1.address(), ptrs[0].address());
            assertEquals(seg2.address(), ptrs[1].address());
        }
    }

    /**
     * Verify that default (both {@code @In} and {@code @Out}) marshalling works.
     * The pointer addresses are copied in before the call and read back after.
     * Since {@code memcpy} does not modify the source, the array should be unchanged.
     */
    @Test
    public void testSegmentArrayInOut() {
        assumeTrue(SegmentArrayTest.class.getModule().isNativeAccessEnabled());
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment seg1 = arena.allocate(8);
            MemorySegment seg2 = arena.allocate(8);
            MemorySegment[] ptrs = { seg1, seg2 };
            long size = 2 * ValueLayout.ADDRESS.byteSize();
            MemorySegment dest = arena.allocate(ValueLayout.ADDRESS, 2);
            copyInOut(dest, ptrs, size);
            // verify the @In copy worked: addresses should be in dest
            assertEquals(seg1.address(), dest.getAtIndex(ValueLayout.ADDRESS, 0).address());
            assertEquals(seg2.address(), dest.getAtIndex(ValueLayout.ADDRESS, 1).address());
            // verify the @Out copy: array should still have the same addresses (memcpy doesn't modify src)
            assertEquals(seg1.address(), ptrs[0].address());
            assertEquals(seg2.address(), ptrs[1].address());
        }
    }

    /**
     * Copy the addresses in {@code src} to the destination buffer using {@code memcpy}.
     *
     * @param dest the destination segment (must not be {@code null})
     * @param src the source array of segments whose addresses are copied in (must not be {@code null})
     * @param size the number of bytes to copy (must not be negative)
     * @return the destination segment
     */
    @Link(name = "memcpy")
    private static native MemorySegment copyIn(MemorySegment dest, @In MemorySegment[] src, long size);

    /**
     * Copy addresses from the source buffer into the output array using {@code memcpy}.
     *
     * @param dest the output array to populate with addresses (must not be {@code null})
     * @param src the source segment containing addresses (must not be {@code null})
     * @param size the number of bytes to copy (must not be negative)
     * @return the destination segment (the marshalled backing segment)
     */
    @Link(name = "memcpy")
    private static native MemorySegment copyOut(@Out MemorySegment[] dest, MemorySegment src, long size);

    /**
     * Copy addresses both in and out using {@code memcpy} (default: both {@code @In} and {@code @Out}).
     *
     * @param dest the destination segment (must not be {@code null})
     * @param src the array of segments, copied in before the call and read back after (must not be {@code null})
     * @param size the number of bytes to copy (must not be negative)
     * @return the destination segment
     */
    @Link(name = "memcpy")
    private static native MemorySegment copyInOut(MemorySegment dest, MemorySegment[] src, long size);
}
