package io.smallrye.ffm.test;

import static org.junit.jupiter.api.Assertions.*;
import static org.junit.jupiter.api.Assumptions.*;

import java.lang.foreign.MemorySegment;

import org.junit.jupiter.api.Test;

import io.smallrye.ffm.Link;

/**
 * Tests for methods with {@code String} parameters that are not in the final position.
 * Reproduces a verification error in bytecode generated by the maven plugin when a
 * {@code MemorySegment} parameter precedes a {@code String} parameter.
 */
public final class StringParamTest {

    /**
     * Construct a new instance.
     */
    public StringParamTest() {
    }

    /**
     * Test that {@code strcmp} works with two consecutive {@code String} parameters.
     */
    @Test
    public void testTwoStringParams() {
        assumeTrue(StringParamTest.class.getModule().isNativeAccessEnabled());
        assertEquals(0, strcmp("hello", "hello"));
        assertTrue(strcmp("abc", "def") < 0);
        assertTrue(strcmp("def", "abc") > 0);
    }

    /**
     * Test that a {@code MemorySegment} parameter followed by a {@code String} parameter
     * followed by another {@code MemorySegment} parameter produces valid bytecode.
     * This exercises the code path where {@link SegmentArgumentStep} wraps subsequent
     * steps inside a {@code block()}.
     */
    @Test
    public void testSegmentStringSegment() {
        assumeTrue(StringParamTest.class.getModule().isNativeAccessEnabled());
        MemorySegment dest = MemorySegment.NULL;
        MemorySegment src = MemorySegment.NULL;
        // just verify that the method can be called without VerifyError
        MemorySegment result = segStringSeg(dest, "hello", src);
    }

    /**
     * Compares two strings lexicographically.
     *
     * @param s1 the first string (must not be {@code null})
     * @param s2 the second string (must not be {@code null})
     * @return a negative value if {@code s1 < s2}, zero if equal, or a positive value if {@code s1 > s2}
     */
    @Link
    private static native int strcmp(String s1, String s2);

    /**
     * A dummy native method with signature {@code (MemorySegment, String, MemorySegment) → MemorySegment}
     * to exercise the bytecode transformation for this parameter pattern.
     *
     * @param dest the destination segment (must not be {@code null})
     * @param str the string parameter (must not be {@code null})
     * @param src the source segment (must not be {@code null})
     * @return a memory segment
     */
    @Link(name = "memcpy")
    private static native MemorySegment segStringSeg(MemorySegment dest, String str, MemorySegment src);
}
